name: Publish Docker image to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
              
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t lc-config-downloader .

      - name: Tag and push images
        run: |
          docker tag lc-config-downloader:latest ghcr.io/${{ github.repository_owner }}/lc-config-downloader:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/lc-config-downloader:${{ github.sha }}
          docker tag lc-config-downloader:latest ghcr.io/${{ github.repository_owner }}/lc-config-downloader:latest
          docker push ghcr.io/${{ github.repository_owner }}/lc-config-downloader:latest
